# Generated by Django 4.1.5 on 2023-01-22 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('content', models.TextField(default=None)),
                ('complete', models.BooleanField(default=False)),
                ('date_posted', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
