# Generated by Django 4.1.5 on 2023-01-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_todo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(default='No Content to Show!'),
        ),
    ]
