# Generated by Django 4.1.5 on 2023-01-23 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_alter_todo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
